### ISSUE TITLE
Create time series exports in JHU format

### ISSUE THREAD

**Issue by cscollett** [tomquisel/covid19-data#11]
Thanks for publishing county data! Please consider making this data available in an additional time series format similar to JHU:

1) It's simpler to update and run using scripted plots with a single Data URL
2) Work already done using the JHU reports could be easily retooled to take advantage of county data again.

Reference:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

**Comment by tomquisel** [comment]
Great suggestion! I'll add this within a week, or of course feel free to submit a PR for this.
